# Network Creation

Let's create a small Neural Network with 3 hidden layers for testing

In [2]:
import numpy as np
import pandas as pd
from nn_utils import *

In [3]:
n_hidden_layers = 3
n_neurons = 5
n_outputs = 3
n_inputs = 10

net = NeuralNetwork()
net.add_input_layer(10)

net.add_hidden_layer(10, 15)
net.add_hidden_layer(15, 14)
net.add_hidden_layer(14, 14)
net.add_output_layer(14, 3)


print(net)
print(net.number_of_nodes())

INPUT LAYER: 
NODE 0 OUTPUT = 0.0
NODE 1 OUTPUT = 0.0
NODE 2 OUTPUT = 0.0
NODE 3 OUTPUT = 0.0
NODE 4 OUTPUT = 0.0
NODE 5 OUTPUT = 0.0
NODE 6 OUTPUT = 0.0
NODE 7 OUTPUT = 0.0
NODE 8 OUTPUT = 0.0
NODE 9 OUTPUT = 0.0

LAYER 0 
NODE 0 WEIGHTS = 0.1368247926554571, 0.019242618963676204, -0.10539762374285126, -0.13168149082780095, 0.28496669503277416, 0.11515940385894877, -0.21470447177810545, 0.008067274604882956, -0.11685692033922959, -0.04486040213895344,  BIAS = 0.0
NODE 1 WEIGHTS = -0.10582819162496113, -0.22192577109099856, 0.4488834165724025, -0.057949007329097135, -0.2690934448720616, 0.43665703372324066, 0.1703559452920295, -0.18100879336964168, 0.3392500702583357, -0.022132563398905434,  BIAS = 0.0
NODE 2 WEIGHTS = -0.3375357473281807, 0.31467313654510226, 0.10178037500122193, 0.38363350285307424, -0.3277300288023779, 0.029166363366834175, 0.24340486587150295, -0.26272902634971307, -0.15037239136072378, -0.08423406071336159,  BIAS = 0.0
NODE 3 WEIGHTS = -0.13925688098832203, -0.236

In [4]:
col_names = ('Input1', 'Input2', 'Input3', 'Input4', 'Input5', 'Input6',
             'Input7', 'Input8', 'Input9', 'Input10', 'TARGET_x', 'TARGET_y', 'TARGET_z')
data = pd.read_csv("../ML-23-PRJ-Package/ML-CUP23-TR.csv",
                   skiprows=7, usecols=[i for i in range(1, 14)], names=col_names)

data

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
0   -0.917280 -0.712727 -0.989904  0.992819  0.993649  0.995543  0.711074   
1   -0.858784  0.998755 -0.998396  0.999909  0.316503 -0.951897 -0.163139   
2   -0.990441  0.958726 -0.998675  0.997216  0.987166  0.356483 -0.279689   
3    0.937117  0.984474 -0.612420  0.999812  0.728623 -0.539962 -0.165939   
4   -0.906628 -0.884567 -0.932487  0.941037  0.978134  0.998179  0.749606   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.803560 -0.878859 -0.978391  0.957539  0.996655  0.996924 -0.226305   
996  0.718841  0.995748 -0.942678  0.999929  0.747763 -0.808726  0.176132   
997 -0.977912 -0.971108  0.956233 -0.979524  0.222033  0.986609  0.658273   
998  0.284803 -0.988684 -0.427197  0.883317  0.993302  0.999500 -0.019456   
999 -0.987580  0.993488 -0.998944  0.999703  0.936830 -0.564176  0.262568   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
0    0.407645 -0.688548  0.616890   7.897453 -35.936382  21.077147  
1    0.980982  0.661759 -0.800155  -9.330632  19.901571   6.069154  
2    0.599163 -0.684630  0.922901  14.849400   3.374090  19.667479  
3    0.999352 -0.921444 -0.974766 -46.591854  13.734777  17.953600  
4   -0.590599 -0.508268  0.691798   8.217500 -45.885254  14.894251  
..        ...       ...       ...        ...        ...        ...  
995  0.097814 -0.922666  0.934153  15.389553 -41.068806  27.513502  
996  0.999100 -0.753970 -0.969009 -36.228770  13.067430  11.672133  
997 -0.987310  0.937697  0.143420   7.265506 -53.497242   2.815666  
998 -0.648110 -0.955231  0.901298   5.545274 -63.348396  27.989340  
999  0.892081 -0.198204  0.494586   6.160610   8.321016  13.021444  

[1000 rows x 13 columns]


# Preparing Dataframe
i.e. creating the training set by removing non-training columns


In [5]:
# shuffle data
data = data.sample(frac=1)

In [6]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
423 -0.994910  0.823880 -0.999124  0.989878  0.988935  0.798326  0.043848   
455  0.863678 -0.986197  0.016546  0.886590  0.995752  0.999574 -0.252772   
148 -0.895234  0.939590 -0.995826  0.999730  0.994012  0.812374  0.372725   
794  0.981785 -0.987896  0.986482 -0.986210  0.945923  0.990865 -0.089256   
683 -0.765332  0.468227 -0.991929  0.993943  0.997743  0.965802 -0.582458   
..        ...       ...       ...       ...       ...       ...       ...   
560  0.400366 -0.989577  0.565986  0.853334  0.992405  0.999663  0.687778   
439  0.957859 -0.974788  0.980466 -0.991948 -0.192474  0.912216  0.124877   
453 -0.997336  0.837674 -0.997175  0.998287  0.878549  0.536548  0.915558   
569 -0.976008 -0.669508 -0.987123  0.969509  0.980199  0.993293  0.593965   
853 -0.993577  0.912208 -0.999026  0.999163  0.985391  0.699283  0.647340   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
423  0.080515 -0.310080  0.949782  15.132887  -6.588049  13.705746  
455 -0.120169 -0.972901  0.777794  -2.406283 -68.219250  34.532753  
148  0.979430 -0.751928 -0.571193  -3.576582   1.204121  25.086851  
794  0.532404 -0.488703 -0.745906 -31.760530 -54.544020  22.622293  
683  0.924112 -0.957458  0.699720  11.586330  -5.317598  33.275753  
..        ...       ...       ...        ...        ...        ...  
560 -0.786044 -0.949340  0.753882   0.069023 -68.780290  21.912683  
439  0.692903  0.609750 -0.989367 -42.671974 -36.559300  10.271296  
453  0.108344  0.805384  0.070636   3.931570  -9.361579   1.817344  
569 -0.339753 -0.354213  0.818584  11.323356 -39.233040  14.863662  
853  0.768952 -0.412104  0.625748   8.053836  -4.936084  14.341548  

[100 rows x 13 columns]

In [9]:
tr_data_X = data[['Input1', 'Input2', 'Input3', 'Input4',
                  'Input5', 'Input6', 'Input7', 'Input8', 'Input9', 'Input10']]

tr_data_Y = data[['TARGET_x', 'TARGET_y', 'TARGET_z']]

# act_fun possible values: "relu", "leaky_relu", "tanh", "sigmoid"

losses = net.train(tr_data_X, tr_data_Y, epochs=100,
                 eta=0.01, clip_value=10000, act_fun="relu")
#print(net)
#print(net.input_layer.weights)

plot_loss(losses)


In [ ]:
np.dot(net.hidden_layers[0].output, net.hidden_layers[1].weights)

array([ 6.6105242 ,  0.08206604, 11.63616897, -3.79270529, -0.71540415,
       -2.27479573, -3.38051083,  2.20958504,  0.51990967,  0.85212392,
       -2.67982063, -1.47384878,  0.31432086, -1.22376506])

In [ ]:
net.output_layer.output

array([-66.11080925, -12.92805092,  31.83028385])

In [ ]:
for row, label in zip(tr_data_X.itertuples(index=False, name=None), tr_data_Y.itertuples(index=False, name=None)):
    # Forward propagation
    net.forwardPropagation( row, label, act_fun = "relu")
    print(np.array(label))
    print(net.output_layer.output)
    break

[-37.83411     -0.14454013   5.457675  ]
[-61.23780684   5.27454664  11.28522755]


In [ ]:
a = np.array([10, -3])

In [ ]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

In [ ]:
leaky_relu(a)

array([10.  , -0.03])

In [ ]:
def clip_gradients(gradients, clip_value):
    clipped_gradients = []
    for gradient in gradients:
        clipped_gradient = np.clip(gradient, -clip_value, clip_value)
        clipped_gradients.append(clipped_gradient)
    return clipped_gradients

In [ ]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
17   0.891745  0.821807  0.925741  0.466906 -0.981792 -0.916250 -0.288479   
954  0.900341  0.840673 -0.373929  0.998566  0.948125  0.855322 -0.349020   
727  0.106918 -0.398283 -0.951825  0.996644  0.995006  0.994797  0.653670   
102  0.932640 -0.992060  0.979284 -0.991983  0.895976  0.981953  0.074303   
12  -0.877142  0.997698 -0.997844  0.999913  0.904342 -0.657521  0.691509   
..        ...       ...       ...       ...       ...       ...       ...   
567  0.919953  0.979687 -0.643724  0.999849  0.819928 -0.081385  0.408615   
26   0.993172  0.829590  0.778088  0.994716  0.151789  0.747123  0.041514   
217  0.199660 -0.990963  0.535124  0.755811  0.991847  0.999655  0.513765   
22   0.975706 -0.916083  0.995357 -0.969456 -0.909366  0.533735  0.559306   
324  0.570808 -0.987593  0.446779  0.903257  0.994394  0.999649  0.809747   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
17   0.986429  0.875373 -0.999734 -37.834110  -0.144540   5.457675  
954  0.998675 -0.952544 -0.955686 -45.983760   0.239661  30.545220  
727  0.968158 -0.618124 -0.912197 -25.173060 -27.135962  22.735708  
102 -0.201555  0.170611 -0.800217 -24.157822 -54.962910  16.238201  
12   0.981739  0.305082 -0.803742 -10.238073   6.206751   5.935548  
..        ...       ...       ...        ...        ...        ...  
567  0.999476 -0.865890 -0.983984 -47.027120   7.362587  18.008200  
26   0.998451 -0.936416 -0.987079 -64.875580   0.602405  23.695478  
217 -0.875172 -0.961479  0.892217   4.102126 -69.388275  21.863165  
22   0.911171  0.377028 -0.997545 -56.643700 -20.640207   4.322106  
324 -0.595506 -0.909799  0.435637  -4.328653 -65.559944  22.305262  

[100 rows x 13 columns]