# Network Creation

Let's create a small Neural Network with 3 hidden layers for testing

In [1]:
import numpy as np
import pandas as pd
from nn_utils import *

In [2]:
n_hidden_layers = 3
n_neurons = 5
n_outputs = 3
n_inputs = 10

net = NeuralNetwork()
net.add_input_layer(10)

net.add_hidden_layer(10, 15)
net.add_hidden_layer(15, 14)
net.add_hidden_layer(14, 14)
net.add_output_layer(14, 3)


print(net)
print(net.number_of_nodes())

INPUT LAYER: 
NODE 0 OUTPUT = 0.0
NODE 1 OUTPUT = 0.0
NODE 2 OUTPUT = 0.0
NODE 3 OUTPUT = 0.0
NODE 4 OUTPUT = 0.0
NODE 5 OUTPUT = 0.0
NODE 6 OUTPUT = 0.0
NODE 7 OUTPUT = 0.0
NODE 8 OUTPUT = 0.0
NODE 9 OUTPUT = 0.0

LAYER 0 
NODE 0 WEIGHTS = -0.15891271491116815, 0.013826089493648979, -0.39111402130337863, -0.054833493004314254, 0.23224171722909795, 0.35817446556592364, 0.2504681444789796, -0.05023711686747556, -0.1499533648435632, 0.07894655299814511,  BIAS = 0.0
NODE 1 WEIGHTS = -0.21056595971193903, -0.011465014854883998, 0.04760104342299494, -0.16233508920979553, 0.04106527457027038, -0.2673820432215912, 0.027856979043705515, 0.30822296380972486, -0.43248193437690047, -0.170009939464059,  BIAS = 0.0
NODE 2 WEIGHTS = -0.0951164173938509, 0.0374215542411505, -0.06316693668285751, 0.06752861767839, -0.23476313450789993, -0.33531419162502973, 0.6991871140962859, -0.23596088606052573, -0.585762515348839, 0.30209653063140796,  BIAS = 0.0
NODE 3 WEIGHTS = -0.09259276231672128, -0.209969939

In [3]:
col_names = ('Input1', 'Input2', 'Input3', 'Input4', 'Input5', 'Input6',
             'Input7', 'Input8', 'Input9', 'Input10', 'TARGET_x', 'TARGET_y', 'TARGET_z')
data = pd.read_csv("../ML-23-PRJ-Package/ML-CUP23-TR.csv",
                   skiprows=7, usecols=[i for i in range(1, 14)], names=col_names)

data

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
0   -0.917280 -0.712727 -0.989904  0.992819  0.993649  0.995543  0.711074   
1   -0.858784  0.998755 -0.998396  0.999909  0.316503 -0.951897 -0.163139   
2   -0.990441  0.958726 -0.998675  0.997216  0.987166  0.356483 -0.279689   
3    0.937117  0.984474 -0.612420  0.999812  0.728623 -0.539962 -0.165939   
4   -0.906628 -0.884567 -0.932487  0.941037  0.978134  0.998179  0.749606   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.803560 -0.878859 -0.978391  0.957539  0.996655  0.996924 -0.226305   
996  0.718841  0.995748 -0.942678  0.999929  0.747763 -0.808726  0.176132   
997 -0.977912 -0.971108  0.956233 -0.979524  0.222033  0.986609  0.658273   
998  0.284803 -0.988684 -0.427197  0.883317  0.993302  0.999500 -0.019456   
999 -0.987580  0.993488 -0.998944  0.999703  0.936830 -0.564176  0.262568   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
0    0.407645 -0.688548  0.616890   7.897453 -35.936382  21.077147  
1    0.980982  0.661759 -0.800155  -9.330632  19.901571   6.069154  
2    0.599163 -0.684630  0.922901  14.849400   3.374090  19.667479  
3    0.999352 -0.921444 -0.974766 -46.591854  13.734777  17.953600  
4   -0.590599 -0.508268  0.691798   8.217500 -45.885254  14.894251  
..        ...       ...       ...        ...        ...        ...  
995  0.097814 -0.922666  0.934153  15.389553 -41.068806  27.513502  
996  0.999100 -0.753970 -0.969009 -36.228770  13.067430  11.672133  
997 -0.987310  0.937697  0.143420   7.265506 -53.497242   2.815666  
998 -0.648110 -0.955231  0.901298   5.545274 -63.348396  27.989340  
999  0.892081 -0.198204  0.494586   6.160610   8.321016  13.021444  

[1000 rows x 13 columns]


# Preparing Dataframe
i.e. creating the training set by removing non-training columns


In [4]:
# shuffle data
data = data.sample(frac=1)

In [5]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
498 -0.946160  0.987935 -0.997599  0.999875  0.983974  0.200464  0.430715   
645 -0.824674 -0.988968  0.984033 -0.972466  0.786001  0.990754  0.840422   
189  0.267519 -0.994195  0.983313 -0.978949  0.936327  0.995880  0.333530   
660  0.999299  0.495354  0.995108  0.709587 -0.676712  0.120844 -0.422403   
686  0.792900 -0.979067 -0.276151  0.954221  0.996758  0.999545  0.514181   
..        ...       ...       ...       ...       ...       ...       ...   
524 -0.987962  0.990669 -0.999071  0.999851  0.973366 -0.135422  0.623435   
845  0.997263  0.846988  0.917538  0.989381 -0.383335  0.392611 -0.495885   
969 -0.995206  0.967224 -0.999204  0.996647  0.959946 -0.195293  0.128486   
148 -0.895234  0.939590 -0.995826  0.999730  0.994012  0.812374  0.372725   
288 -0.872592 -0.991890  0.986255 -0.993175  0.838377  0.994625  0.783413   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
498  0.978815 -0.396716 -0.676438  -4.629166   5.720070  18.844450  
645 -0.974888  0.774420 -0.351285  -1.796867 -61.473990   2.792147  
189 -0.947504  0.471363 -0.305722  -9.234951 -64.270584   9.712447  
660  0.990082 -0.904127 -0.991888 -75.835640   5.937950  17.395266  
686  0.149045 -0.892959  0.283220  -9.089668 -59.248383  28.738980  
..        ...       ...       ...        ...        ...        ...  
524  0.919091 -0.195228  0.022779   2.460534   4.230272  12.612555  
845  0.997792 -0.980388 -0.976241 -72.199936   8.785388  23.690440  
969  0.057472  0.053963  0.955668  12.972487   2.680447   7.559412  
148  0.979430 -0.751928 -0.571193  -3.576582   1.204121  25.086851  
288 -0.991757  0.493380  0.536468   7.948854 -65.841490   2.901068  

[100 rows x 13 columns]

In [6]:
tr_data_X = data[['Input1', 'Input2', 'Input3', 'Input4',
                  'Input5', 'Input6', 'Input7', 'Input8', 'Input9', 'Input10']]

tr_data_Y = data[['TARGET_x', 'TARGET_y', 'TARGET_z']]

# act_fun possible values: "relu", "leaky_relu", "tanh", "sigmoid"

losses = net.train(tr_data_X, tr_data_Y, epochs=100,
                 eta=0.01, clip_value=10000, hid_act_fun="relu", out_act_fun = "linear", cost_fun="mse")
#print(net)
#print(net.input_layer.weights)

plot_loss(losses, cost_fun="mse")


total Error pre-training = 1152.4196112811098


Epoch = 1, total Error post-training = 1142.8875074722673
Epoch = 2, total Error post-training = 1125.673037769971
Epoch = 3, total Error post-training = 1077.0842613513068
Epoch = 4, total Error post-training = 943.0050336594189


KeyboardInterrupt: 

In [ ]:
np.dot(net.hidden_layers[0].output, net.hidden_layers[1].weights)

array([ 0.92386893,  4.65036814,  3.4656541 , -1.94489014, -0.89784559,
        2.0892068 , -3.33149471,  1.84034483, -2.72281213, -3.45746103,
        2.85937109, -0.78413409,  0.13635383,  4.28649052])

In [ ]:
net.output_layer.output

array([  8.03963634, -13.69481415,  18.51180373])

In [ ]:
for row, label in zip(tr_data_X.itertuples(index=False, name=None), tr_data_Y.itertuples(index=False, name=None)):
    # Forward propagation
    net.forwardPropagation( row, label, hid_act_fun = "relu")
    print(np.array(label))
    print(net.output_layer.output)
    break

TypeError: NeuralNetwork.forwardPropagation() missing 2 required positional arguments: 'out_act_fun' and 'cost_fun'

In [ ]:
a = np.array([10, -3])

In [ ]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

In [ ]:
leaky_relu(a)

array([10.  , -0.03])

In [ ]:
def clip_gradients(gradients, clip_value):
    clipped_gradients = []
    for gradient in gradients:
        clipped_gradient = np.clip(gradient, -clip_value, clip_value)
        clipped_gradients.append(clipped_gradient)
    return clipped_gradients

In [ ]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
877  0.972025  0.410580  0.375335  0.981677  0.821849  0.976445  0.370172   
596 -0.921641  0.996916 -0.996585  0.999201  0.695600 -0.827381 -0.859343   
785 -0.945496 -0.849870 -0.982610  0.845478  0.989746  0.995534 -0.132807   
299 -0.847125  0.958732 -0.992248  0.999134  0.991583  0.658474 -0.571817   
341 -0.752110 -0.981380  0.628611  0.186702  0.973617  0.999561  0.796431   
..        ...       ...       ...       ...       ...       ...       ...   
666  0.906358 -0.981578  0.049691  0.899411  0.996555  0.999568 -0.161929   
444  0.611861 -0.983134  0.971809 -0.993658 -0.081964  0.903549  0.767277   
247  0.727043  0.993637 -0.933711  0.999906  0.842716 -0.688792 -0.382051   
340 -0.995151  0.992387 -0.999513  0.999562  0.784210 -0.811411  0.656836   
442 -0.815612  0.984780 -0.995201  0.999855  0.986613  0.308997 -0.044228   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
877  0.997125 -0.801826 -0.990364 -55.809105 -10.995221  23.190393  
596  0.962592 -0.283151  0.088003   4.885140  23.510721  25.254839  
785 -0.595489 -0.749627  0.967288  17.255964 -43.981915  21.283264  
299  0.979084 -0.912930 -0.018332   3.743294   7.814204  32.018210  
341 -0.953215 -0.696914  0.831464   7.501262 -64.925200   9.403218  
..        ...       ...       ...        ...        ...        ...  
666  0.234609 -0.957945  0.554906  -7.748474 -64.517270  34.682960  
444 -0.646714  0.932248 -0.942574 -24.396614 -44.692210   3.768535  
247  0.999030 -0.851263 -0.955829 -35.623497  15.541903  18.137384  
340  0.317082  0.613851  0.812395   7.300842   5.234912   0.986290  
442  0.991955 -0.725049 -0.788047  -8.715402   8.472854  24.762306  

[100 rows x 13 columns]