# Network Creation

Let's create a small Neural Network with 3 hidden layers for testing

In [1]:
import numpy as np
import pandas as pd
from nn_utils import *

In [2]:
n_hidden_layers = 3
n_neurons = 5
n_outputs = 3
n_inputs = 10

net = NeuralNetwork()
net.add_input_layer(10)

net.add_hidden_layer(10, 5)
net.add_hidden_layer(5, 4)
net.add_hidden_layer(4, 3)

net.add_output_layer(3, 3)


print(net)
print(net.number_of_nodes())





INPUT LAYER: 
NODE 0 WEIGHTS = 1.764052345967664,  BIAS = 0.0
NODE 1 WEIGHTS = 0.4001572083672233,  BIAS = 0.0
NODE 2 WEIGHTS = 0.9787379841057392,  BIAS = 0.0
NODE 3 WEIGHTS = 2.240893199201458,  BIAS = 0.0
NODE 4 WEIGHTS = 1.8675579901499675,  BIAS = 0.0
NODE 5 WEIGHTS = -0.977277879876411,  BIAS = 0.0
NODE 6 WEIGHTS = 0.9500884175255894,  BIAS = 0.0
NODE 7 WEIGHTS = -0.1513572082976979,  BIAS = 0.0
NODE 8 WEIGHTS = -0.10321885179355784,  BIAS = 0.0
NODE 9 WEIGHTS = 0.41059850193837233,  BIAS = 0.0

LAYER 0 
NODE 0 WEIGHTS = 0.144043571160878, 0.33367432737426683, -2.5529898158340787, -1.4543656745987648, 0.1549474256969163, 0.15634896910398005, -1.0485529650670926, -0.4380743016111864, -0.8954665611936756, 0.42833187053041766,  BIAS = 0.0
NODE 1 WEIGHTS = 1.454273506962975, 1.4940790731576061, 0.6536185954403606, 0.04575851730144607, 0.37816251960217356, 1.2302906807277207, -1.4200179371789752, -1.2527953600499262, 0.386902497859262, 0.06651722238316789,  BIAS = 0.0
NODE 2 WEIGHTS =

In [3]:
col_names = ('Input1', 'Input2', 'Input3', 'Input4', 'Input5', 'Input6', 'Input7', 'Input8', 'Input9', 'Input10', 'TARGET_x', 'TARGET_y', 'TARGET_z')
data = pd.read_csv("../ML-23-PRJ-Package/ML-CUP23-TR.csv", skiprows=7, usecols = [i for i in range (1, 14)], names = col_names)

data

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
0   -0.917280 -0.712727 -0.989904  0.992819  0.993649  0.995543  0.711074   
1   -0.858784  0.998755 -0.998396  0.999909  0.316503 -0.951897 -0.163139   
2   -0.990441  0.958726 -0.998675  0.997216  0.987166  0.356483 -0.279689   
3    0.937117  0.984474 -0.612420  0.999812  0.728623 -0.539962 -0.165939   
4   -0.906628 -0.884567 -0.932487  0.941037  0.978134  0.998179  0.749606   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.803560 -0.878859 -0.978391  0.957539  0.996655  0.996924 -0.226305   
996  0.718841  0.995748 -0.942678  0.999929  0.747763 -0.808726  0.176132   
997 -0.977912 -0.971108  0.956233 -0.979524  0.222033  0.986609  0.658273   
998  0.284803 -0.988684 -0.427197  0.883317  0.993302  0.999500 -0.019456   
999 -0.987580  0.993488 -0.998944  0.999703  0.936830 -0.564176  0.262568   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
0    0.407645 -0.688548  0.616890   7.897453 -35.936382  21.077147  
1    0.980982  0.661759 -0.800155  -9.330632  19.901571   6.069154  
2    0.599163 -0.684630  0.922901  14.849400   3.374090  19.667479  
3    0.999352 -0.921444 -0.974766 -46.591854  13.734777  17.953600  
4   -0.590599 -0.508268  0.691798   8.217500 -45.885254  14.894251  
..        ...       ...       ...        ...        ...        ...  
995  0.097814 -0.922666  0.934153  15.389553 -41.068806  27.513502  
996  0.999100 -0.753970 -0.969009 -36.228770  13.067430  11.672133  
997 -0.987310  0.937697  0.143420   7.265506 -53.497242   2.815666  
998 -0.648110 -0.955231  0.901298   5.545274 -63.348396  27.989340  
999  0.892081 -0.198204  0.494586   6.160610   8.321016  13.021444  

[1000 rows x 13 columns]


# Preparing Dataframe
i.e. creating the training set by removing non-training columns


In [4]:
tr_data_X = data[['Input1', 'Input2', 'Input3', 'Input4', 'Input5', 'Input6', 'Input7', 'Input8', 'Input9', 'Input10']]

tr_data_Y = data[['TARGET_x', 'TARGET_y', 'TARGET_z']]

net.train(tr_data_X,tr_data_Y,epochs=100)

print(net)
print(net.input_layer.weights)


total Error pre-training = 0.14079026392645735
1000
Epoch = 1, total Error post-training = 1.3635661049309102
1000
Epoch = 2, total Error post-training = 0.1407902617393093
1000
Epoch = 3, total Error post-training = 0.1407902617393093
1000
Epoch = 4, total Error post-training = 0.134476252810022
1000
Epoch = 5, total Error post-training = 0.09830974353543169
1000
Epoch = 6, total Error post-training = 0.07731962368409626
1000
Epoch = 7, total Error post-training = 0.06561110384676347
1000
Epoch = 8, total Error post-training = 0.059497776644888006
1000
Epoch = 9, total Error post-training = 0.056689347630901714
1000
Epoch = 10, total Error post-training = 0.055775233378121694
1000
Epoch = 11, total Error post-training = 0.05589682450927946
1000
Epoch = 12, total Error post-training = 0.05653994223557
1000
Epoch = 13, total Error post-training = 0.05740377710227561
1000
Epoch = 14, total Error post-training = 0.05831842303447091
1000
Epoch = 15, total Error post-training = 0.0591932297

In [5]:
net.hidden_layers[0].acc_bias_gradients

array([0., 0., 0., 0., 0.])

In [6]:
for row,label in zip(tr_data_X.itertuples(index = False, name = None),tr_data_Y.itertuples(index=False,name=None)):
    #Forward propagation
    net.forwardPropagation(row,label)
    print(np.array(label))
    print(net.output_layer.output)
    break
          

[  7.897453 -35.936382  21.077147]
[-0.         -0.         17.09215318]
