# Network Creation

Let's create a small Neural Network with 3 hidden layers for testing

In [1]:
import numpy as np
import pandas as pd
from nn_utils import *

In [2]:
n_hidden_layers = 3
n_neurons = 5
n_outputs = 3
n_inputs = 10

net = NeuralNetwork()
net.add_input_layer(10)

net.add_hidden_layer(10, 5)
net.add_hidden_layer(5, 4)
net.add_hidden_layer(4, 4)
net.add_output_layer(4, 3)


print(net)
print(net.number_of_nodes())

INPUT LAYER: 
NODE 0 OUTPUT = 0.0
NODE 1 OUTPUT = 0.0
NODE 2 OUTPUT = 0.0
NODE 3 OUTPUT = 0.0
NODE 4 OUTPUT = 0.0
NODE 5 OUTPUT = 0.0
NODE 6 OUTPUT = 0.0
NODE 7 OUTPUT = 0.0
NODE 8 OUTPUT = 0.0
NODE 9 OUTPUT = 0.0

LAYER 0 
NODE 0 WEIGHTS = -0.5336265113717606, 0.004750176565380758, -0.29733964867992785, 0.0475509744594604, -0.11006579178527244, 0.10394241974333814, -0.04348094551265652, -0.06103258331165489, -0.6694087282277381, 0.569884588085982,  BIAS = 0.0
NODE 1 WEIGHTS = 0.3053737038547268, 0.2703839126567841, -0.444666816343709, 0.07458978085173527, -0.4509588537670498, 0.6065456280104796, -0.30229547040374755, 0.11154287373788098, 0.21555616965300123, -0.049179738511156784,  BIAS = 0.0
NODE 2 WEIGHTS = -0.321597508281269, -0.39631460903569454, 0.08968873620279907, -0.6032005088759007, 0.42433460755652896, -0.40266772288891456, 0.18078108831705184, 0.05219440855280601, -0.4546453089484015, 0.5738893045649072,  BIAS = 0.0
NODE 3 WEIGHTS = -0.15077694579085735, -0.4787289011900583

In [3]:
col_names = ('Input1', 'Input2', 'Input3', 'Input4', 'Input5', 'Input6',
             'Input7', 'Input8', 'Input9', 'Input10', 'TARGET_x', 'TARGET_y', 'TARGET_z')
data = pd.read_csv("../ML-23-PRJ-Package/ML-CUP23-TR.csv",
                   skiprows=7, usecols=[i for i in range(1, 14)], names=col_names)

data

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
0   -0.917280 -0.712727 -0.989904  0.992819  0.993649  0.995543  0.711074   
1   -0.858784  0.998755 -0.998396  0.999909  0.316503 -0.951897 -0.163139   
2   -0.990441  0.958726 -0.998675  0.997216  0.987166  0.356483 -0.279689   
3    0.937117  0.984474 -0.612420  0.999812  0.728623 -0.539962 -0.165939   
4   -0.906628 -0.884567 -0.932487  0.941037  0.978134  0.998179  0.749606   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.803560 -0.878859 -0.978391  0.957539  0.996655  0.996924 -0.226305   
996  0.718841  0.995748 -0.942678  0.999929  0.747763 -0.808726  0.176132   
997 -0.977912 -0.971108  0.956233 -0.979524  0.222033  0.986609  0.658273   
998  0.284803 -0.988684 -0.427197  0.883317  0.993302  0.999500 -0.019456   
999 -0.987580  0.993488 -0.998944  0.999703  0.936830 -0.564176  0.262568   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
0    0.407645 -0.688548  0.616890   7.897453 -35.936382  21.077147  
1    0.980982  0.661759 -0.800155  -9.330632  19.901571   6.069154  
2    0.599163 -0.684630  0.922901  14.849400   3.374090  19.667479  
3    0.999352 -0.921444 -0.974766 -46.591854  13.734777  17.953600  
4   -0.590599 -0.508268  0.691798   8.217500 -45.885254  14.894251  
..        ...       ...       ...        ...        ...        ...  
995  0.097814 -0.922666  0.934153  15.389553 -41.068806  27.513502  
996  0.999100 -0.753970 -0.969009 -36.228770  13.067430  11.672133  
997 -0.987310  0.937697  0.143420   7.265506 -53.497242   2.815666  
998 -0.648110 -0.955231  0.901298   5.545274 -63.348396  27.989340  
999  0.892081 -0.198204  0.494586   6.160610   8.321016  13.021444  

[1000 rows x 13 columns]


# Preparing Dataframe
i.e. creating the training set by removing non-training columns


In [4]:
# shuffle data
data = data.sample(frac=1)

In [5]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
3    0.937117  0.984474 -0.612420  0.999812  0.728623 -0.539962 -0.165939   
46  -0.975342  0.099676 -0.995242  0.998623  0.977413  0.969347  0.926281   
803  0.644077 -0.968200 -0.773163  0.955951  0.997316  0.999437 -0.230699   
624  0.789954 -0.991294  0.700572  0.795240  0.993062  0.999629  0.273810   
839 -0.752728 -0.968223 -0.558908  0.803738  0.982758  0.999324  0.725560   
..        ...       ...       ...       ...       ...       ...       ...   
282  0.996989  0.479188  0.983181  0.513208 -0.932694 -0.579042 -0.616787   
628  0.898516 -0.947417 -0.270351  0.906145  0.995084  0.999118  0.088077   
360 -0.389235 -0.996068  0.994351 -0.981156  0.944517  0.996256  0.890311   
499 -0.710840  0.997581 -0.997162  0.999925  0.888776 -0.796745  0.002688   
210  0.991915  0.741575  0.789426  0.988341  0.412714  0.853500 -0.448465   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
3    0.999352 -0.921444 -0.974766 -46.591854  13.734777  17.953600  
46   0.643563 -0.001748  0.126666   3.848626 -24.709364  14.751896  
803  0.390928 -0.946572  0.602025  -0.796520 -55.217205  34.090096  
624 -0.668665 -0.975947  0.784151  -1.938988 -74.325860  28.153563  
839 -0.851897 -0.762830  0.813606   8.020777 -54.535797  15.222616  
..        ...       ...       ...        ...        ...        ...  
282  0.989514 -0.297196 -0.999174 -62.979916   2.331560  11.229145  
628  0.760714 -0.746071 -0.645169 -27.297730 -43.879105  28.869574  
360 -0.978639 -0.133048  0.243922  -1.811200 -73.568650   3.176866  
499  0.993274 -0.152942 -0.841241 -13.103687  12.676478  12.138286  
210  0.998077 -0.961675 -0.973599 -65.408280  -0.610249  29.721237  

[100 rows x 13 columns]

In [6]:
tr_data_X = data[['Input1', 'Input2', 'Input3', 'Input4',
                  'Input5', 'Input6', 'Input7', 'Input8', 'Input9', 'Input10']]

tr_data_Y = data[['TARGET_x', 'TARGET_y', 'TARGET_z']]

# act_fun possible values: "relu", "leaky_relu", "tanh", "sigmoid"

losses = net.train(tr_data_X, tr_data_Y, epochs=100,
                 eta=0.01, clip_value=None, act_fun="tanh")
print(net)
print(net.input_layer.weights)

plot_loss(losses)


total Error pre-training = 1145.5451807818904


Epoch = 1, total Error post-training = 1136.881045054284
Epoch = 2, total Error post-training = 1125.7572221702956
Epoch = 3, total Error post-training = 1114.0273952752414
Epoch = 4, total Error post-training = 1101.3492522987672
Epoch = 5, total Error post-training = 1087.7861453223657
Epoch = 6, total Error post-training = 1073.4290522744927
Epoch = 7, total Error post-training = 1058.3936124994066
Epoch = 8, total Error post-training = 1042.799833606284
Epoch = 9, total Error post-training = 1026.7491730076033
Epoch = 10, total Error post-training = 1010.3128951563359
Epoch = 11, total Error post-training = 993.5270343733339
Epoch = 12, total Error post-training = 976.4248091620984
Epoch = 13, total Error post-training = 959.049510912905
Epoch = 14, total Error post-training = 941.462022401258


KeyboardInterrupt: 

In [ ]:
np.dot(net.hidden_layers[0].output, net.hidden_layers[1].weights)

array([-2.90232849, -3.28281844,  5.40691046, -2.21365389])

In [ ]:
net.output_layer.output

array([  22.66308234, -155.53247548,   21.93495938])

In [ ]:
for row, label in zip(tr_data_X.itertuples(index=False, name=None), tr_data_Y.itertuples(index=False, name=None)):
    # Forward propagation
    net.forwardPropagation(row, label)
    print(np.array(label))
    print(net.output_layer.output)
    break

TypeError: NeuralNetwork.forwardPropagation() missing 1 required positional argument: 'act_fun'

In [ ]:
a = np.array([10, -3])

In [ ]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

In [ ]:
leaky_relu(a)

array([10.  , -0.03])

In [ ]:
def clip_gradients(gradients, clip_value):
    clipped_gradients = []
    for gradient in gradients:
        clipped_gradient = np.clip(gradient, -clip_value, clip_value)
        clipped_gradients.append(clipped_gradient)
    return clipped_gradients

In [ ]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
583 -0.928249  0.951282 -0.994961  0.995800  0.988008  0.557033 -0.835346   
198  0.930370 -0.984753  0.366865  0.864926  0.996169  0.999569 -0.121303   
829 -0.991909  0.995544 -0.999462  0.999783  0.662431 -0.860960  0.686519   
121 -0.875395 -0.017366 -0.995372  0.998029  0.997836  0.986808  0.352246   
390 -0.874698  0.882065 -0.993418  0.996505  0.994277  0.817619 -0.736979   
..        ...       ...       ...       ...       ...       ...       ...   
142  0.006589  0.947802 -0.974622  0.999639  0.987982  0.731236 -0.391920   
878  0.427549 -0.992908  0.290578  0.662139  0.991881  0.999557 -0.144159   
254 -0.990265 -0.823980  0.746333 -0.892518 -0.684035  0.938868  0.163099   
467 -0.814592  0.416405 -0.993212  0.992516  0.997602  0.966170 -0.602528   
85  -0.995415  0.977649 -0.999333  0.999637  0.968492  0.150674  0.814360   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
583  0.889854 -0.905005  0.814558  13.961784   8.228383  32.337140  
198  0.159182 -0.963169  0.550347  -9.777412 -67.524315  34.563560  
829  0.621043  0.653304  0.582378   4.519991   6.869997   1.312744  
121  0.899281 -0.882904  0.383765   6.655642 -20.329067  27.133291  
390  0.932532 -0.943479  0.699712  11.841374   4.492530  32.889477  
..        ...       ...       ...        ...        ...        ...  
142  0.996879 -0.932851 -0.857666 -21.871680   6.645402  30.904726  
878 -0.850889 -0.977375  0.949945   6.520555 -72.246735  28.208416  
254 -0.974384  0.990203 -0.583426   3.194378 -35.984486   2.199761  
467  0.898566 -0.951395  0.772447  13.299667  -6.438751  33.147747  
85   0.754517  0.169587  0.462741   4.886172  -1.136713   7.777908  

[100 rows x 13 columns]