# Network Creation

Let's create a small Neural Network with 3 hidden layers for testing

In [1]:
import numpy as np
import pandas as pd
from nn_utils import *

In [32]:
n_hidden_layers = 3
n_neurons = 5
n_outputs = 3
n_inputs = 10

net = NeuralNetwork()
net.add_input_layer(10)

net.add_hidden_layer(10, 5)
net.add_hidden_layer(5, 4)
net.add_hidden_layer(4, 4)
net.add_output_layer(4, 3)


print(net)
print(net.number_of_nodes())





INPUT LAYER: 
NODE 0 OUTPUT = 0.0
NODE 1 OUTPUT = 0.0
NODE 2 OUTPUT = 0.0
NODE 3 OUTPUT = 0.0
NODE 4 OUTPUT = 0.0
NODE 5 OUTPUT = 0.0
NODE 6 OUTPUT = 0.0
NODE 7 OUTPUT = 0.0
NODE 8 OUTPUT = 0.0
NODE 9 OUTPUT = 0.0

LAYER 0 
NODE 0 WEIGHTS = 0.5115899537865142, -0.06620903819305667, -0.312462083560423, 0.7954081238600914, 0.14255258609767382, -0.33058272318812093, -0.1094363066129328, 0.563885315739241, -0.0583651315740952, 0.20626147436399236,  BIAS = 0.0
NODE 1 WEIGHTS = 0.9945501484583128, -0.2917092417309499, -0.2765206435889965, 0.19413080948850225, -0.024996982457316717, 0.1353679634348101, -1.0667507980637039, 0.47288937222304783, -0.2188761951134861, -0.05339200647372138,  BIAS = 0.0
NODE 2 WEIGHTS = 0.4751072177891516, -0.19800708712521686, 0.4836229803628637, 0.25784313122263036, -0.5189231500382266, -0.11167097345157082, 0.12658024477605412, 0.2981328460122707, 0.2646640780448377, 0.3572329679299059,  BIAS = 0.0
NODE 3 WEIGHTS = -0.23919285448609184, 0.5167195203941463, -0.17

In [33]:
col_names = ('Input1', 'Input2', 'Input3', 'Input4', 'Input5', 'Input6', 'Input7', 'Input8', 'Input9', 'Input10', 'TARGET_x', 'TARGET_y', 'TARGET_z')
data = pd.read_csv("../ML-23-PRJ-Package/ML-CUP23-TR.csv", skiprows=7, usecols = [i for i in range (1, 14)], names = col_names)

data

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
0   -0.917280 -0.712727 -0.989904  0.992819  0.993649  0.995543  0.711074   
1   -0.858784  0.998755 -0.998396  0.999909  0.316503 -0.951897 -0.163139   
2   -0.990441  0.958726 -0.998675  0.997216  0.987166  0.356483 -0.279689   
3    0.937117  0.984474 -0.612420  0.999812  0.728623 -0.539962 -0.165939   
4   -0.906628 -0.884567 -0.932487  0.941037  0.978134  0.998179  0.749606   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.803560 -0.878859 -0.978391  0.957539  0.996655  0.996924 -0.226305   
996  0.718841  0.995748 -0.942678  0.999929  0.747763 -0.808726  0.176132   
997 -0.977912 -0.971108  0.956233 -0.979524  0.222033  0.986609  0.658273   
998  0.284803 -0.988684 -0.427197  0.883317  0.993302  0.999500 -0.019456   
999 -0.987580  0.993488 -0.998944  0.999703  0.936830 -0.564176  0.262568   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
0    0.407645 -0.688548  0.616890   7.897453 -35.936382  21.077147  
1    0.980982  0.661759 -0.800155  -9.330632  19.901571   6.069154  
2    0.599163 -0.684630  0.922901  14.849400   3.374090  19.667479  
3    0.999352 -0.921444 -0.974766 -46.591854  13.734777  17.953600  
4   -0.590599 -0.508268  0.691798   8.217500 -45.885254  14.894251  
..        ...       ...       ...        ...        ...        ...  
995  0.097814 -0.922666  0.934153  15.389553 -41.068806  27.513502  
996  0.999100 -0.753970 -0.969009 -36.228770  13.067430  11.672133  
997 -0.987310  0.937697  0.143420   7.265506 -53.497242   2.815666  
998 -0.648110 -0.955231  0.901298   5.545274 -63.348396  27.989340  
999  0.892081 -0.198204  0.494586   6.160610   8.321016  13.021444  

[1000 rows x 13 columns]


# Preparing Dataframe
i.e. creating the training set by removing non-training columns


In [34]:
#shuffle data
data= data.sample(frac = 1)

In [35]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
724 -0.991079  0.995911 -0.999412  0.999816  0.643749 -0.862200  0.724865   
812 -0.887220  0.995610 -0.995969  0.999738  0.914971 -0.564150 -0.681326   
101 -0.007175 -0.988285  0.779468  0.539949  0.987519  0.999678  0.702475   
467 -0.814592  0.416405 -0.993212  0.992516  0.997602  0.966170 -0.602528   
986 -0.802217 -0.720206 -0.989825  0.993608  0.998111  0.996036  0.231096   
..        ...       ...       ...       ...       ...       ...       ...   
216 -0.845218  0.992469 -0.992975  0.999251  0.922371 -0.356120 -0.887543   
225  0.970515 -0.962507  0.325911  0.666332  0.989748  0.999041 -0.053332   
696 -0.521867 -0.969147 -0.423863  0.933890  0.987006  0.999470  0.902434   
739 -0.988470  0.979220 -0.998825  0.996408  0.973160 -0.166102 -0.541943   
432 -0.959080  0.728521 -0.997107  0.996897  0.995382  0.908287 -0.226811   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
724  0.674619  0.665884  0.502101   3.557208   6.750298   0.911574  
812  0.986655 -0.597107 -0.401082  -0.384599  18.456870  25.090982  
101 -0.924877 -0.925840  0.841876   3.301474 -70.909510  15.692393  
467  0.898566 -0.951395  0.772447  13.299667  -6.438751  33.147747  
986  0.758901 -0.907321  0.667307   9.340111 -32.600887  27.397417  
..        ...       ...       ...        ...        ...        ...  
216  0.981169 -0.814411 -0.031282   3.591400  18.856668  31.612738  
225  0.832879 -0.778358 -0.766347 -34.105970 -44.575420  29.010536  
696 -0.709152 -0.699953  0.397387   1.913990 -56.535732  15.296669  
739  0.568974 -0.464674  0.938911  14.994783   8.868770  19.571455  
432  0.858683 -0.885936  0.757273  11.942022  -3.443196  26.838408  

[100 rows x 13 columns]

In [69]:
tr_data_X = data[['Input1', 'Input2', 'Input3', 'Input4', 'Input5', 'Input6', 'Input7', 'Input8', 'Input9', 'Input10']]

tr_data_Y = data[['TARGET_x', 'TARGET_y', 'TARGET_z']]

net.train(tr_data_X,tr_data_Y,epochs=100,eta=10,clip_value=3)

print(net)
print(net.input_layer.weights)


total Error pre-training = 78.17518665689107
Epoch = 1, total Error post-training = 78.6495562403483
Epoch = 2, total Error post-training = 78.08610397719735
Epoch = 3, total Error post-training = 78.47496333605449
Epoch = 4, total Error post-training = 78.0910036376281
Epoch = 5, total Error post-training = 78.48359964804925
Epoch = 6, total Error post-training = 78.0831725586611
Epoch = 7, total Error post-training = 78.47941296508647
Epoch = 8, total Error post-training = 78.07980671602868
Epoch = 9, total Error post-training = 78.47457497911682
Epoch = 10, total Error post-training = 78.07587956257552
Epoch = 11, total Error post-training = 78.46877443927903
Epoch = 12, total Error post-training = 78.08213764348032
Epoch = 13, total Error post-training = 78.48134314561156
Epoch = 14, total Error post-training = 78.07768683633864
Epoch = 15, total Error post-training = 78.46241737512375
Epoch = 16, total Error post-training = 78.06204264223169
Epoch = 17, total Error post-training =

In [7]:
np.dot(net.hidden_layers[0].output,net.hidden_layers[1].weights)

array([ 0.65258382, -0.2029207 , -0.79476457,  1.29149273])

In [64]:
net.output_layer.output

array([ 3.2647808 ,  9.61318696, 14.72462303])

In [10]:
for row,label in zip(tr_data_X.itertuples(index = False, name = None),tr_data_Y.itertuples(index=False,name=None)):
    #Forward propagation
    net.forwardPropagation(row,label)
    print(np.array(label))
    print(net.output_layer.output)
    break
          

[10.421577  -3.0666203 33.06585  ]
[-0. -0. -0.]


In [41]:
a=np.array([10,-3])

In [44]:
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

In [45]:
leaky_relu(a)

array([10.  , -0.03])

In [9]:
def clip_gradients(gradients, clip_value):
    clipped_gradients = []
    for gradient in gradients:
        clipped_gradient = np.clip(gradient, -clip_value, clip_value)
        clipped_gradients.append(clipped_gradient)
    return clipped_gradients

In [10]:
data[:100]

Input1    Input2    Input3    Input4    Input5    Input6    Input7  \
657 -0.998453  0.658892 -0.998845  0.982045  0.920017  0.563095  0.541656   
488 -0.985317  0.997468 -0.999377  0.999834  0.376055 -0.921293  0.464664   
328 -0.590843  0.972962 -0.992528  0.999842  0.989463  0.597601  0.208438   
240 -0.995287  0.992495 -0.999591  0.998925  0.445535 -0.919534  0.339335   
526  0.988079 -0.921678  0.994089 -0.988022 -0.455952  0.900037 -0.468826   
..        ...       ...       ...       ...       ...       ...       ...   
552 -0.808446  0.997782 -0.996666  0.999853  0.790430 -0.852707 -0.637479   
1   -0.858784  0.998755 -0.998396  0.999909  0.316503 -0.951897 -0.163139   
932  0.868000 -0.964759  0.979622 -0.991525 -0.597118  0.842939  0.596226   
470 -0.994836  0.937008 -0.999114  0.998729  0.985795  0.594237  0.446856   
459  0.924457 -0.980545  0.987207 -0.992408 -0.266030  0.897476  0.682903   

       Input8    Input9   Input10   TARGET_x   TARGET_y   TARGET_z  
657 -0.493099  0.885601  0.714244  15.233251 -12.591269   1.999460  
488  0.816497  0.792718  0.057837   1.905639  12.526800   1.011841  
328  0.994900 -0.792296 -0.890330 -15.689543   5.072209  24.796995  
240 -0.086700  0.746722  0.833070  11.749382  10.043569   0.384458  
526  0.956225 -0.051425 -0.994932 -56.147198 -23.977901  16.755610  
..        ...       ...       ...        ...        ...        ...  
552  0.990744 -0.232428 -0.686253  -7.665466  20.006077  18.555740  
1    0.980982  0.661759 -0.800155  -9.330632  19.901571   6.069154  
932  0.311646  0.888234 -0.989825 -38.107357 -34.218254   3.939503  
470  0.662680 -0.441588  0.795250  10.320108  -2.865674  14.167924  
459  0.450343  0.645194 -0.984563 -41.607536 -38.586094   3.952897  

[100 rows x 13 columns]